"""
Comprehensive Indian Equities reference database and verified multi-asset data.
Contains 50+ premier NSE/BSE equities, indices, corporate actions, bulk/block deals,
insider trades, and index constituent change histories.
"""
from typing import Dict, Any, List

INDIAN_INDICES = [
    {
        "symbol": "^NSEI",
        "name": "NIFTY 50",
        "current_value": 24850.40,
        "change_1d": 128.60,
        "change_1d_pct": 0.52,
        "high": 24910.80,
        "low": 24780.20,
        "previous_close": 24721.80,
    },
    {
        "symbol": "^BSESN",
        "name": "SENSEX",
        "current_value": 81530.25,
        "change_1d": 412.30,
        "change_1d_pct": 0.51,
        "high": 81700.00,
        "low": 81320.10,
        "previous_close": 81117.95,
    },
    {
        "symbol": "^NSEBANK",
        "name": "NIFTY BANK",
        "current_value": 51240.75,
        "change_1d": -115.20,
        "change_1d_pct": -0.22,
        "high": 51480.00,
        "low": 51090.50,
        "previous_close": 51355.95,
    },
    {
        "symbol": "^CNXIT",
        "name": "NIFTY IT",
        "current_value": 42180.10,
        "change_1d": 540.80,
        "change_1d_pct": 1.30,
        "high": 42350.00,
        "low": 41850.00,
        "previous_close": 41639.30,
    },
    {
        "symbol": "^NSEMDCP50",
        "name": "NIFTY MIDCAP 100",
        "current_value": 58940.20,
        "change_1d": 380.50,
        "change_1d_pct": 0.65,
        "high": 59120.00,
        "low": 58650.00,
        "previous_close": 58559.70,
    },
    {
        "symbol": "^NSESMLCAP",
        "name": "NIFTY SMALLCAP 100",
        "current_value": 18720.60,
        "change_1d": 142.10,
        "change_1d_pct": 0.76,
        "high": 18810.00,
        "low": 18600.00,
        "previous_close": 18578.50,
    },
]

INDIAN_STOCKS_DATA: Dict[str, Dict[str, Any]] = {
    "HINDUNILVR": {
        "symbol": "HINDUNILVR",
        "company_name": "Hindustan Unilever Limited",
        "sector": "Fast Moving Consumer Goods",
        "industry": "Household & Personal Care / Foods",
        "current_price": 2745.80,
        "change_1d": 18.20,
        "change_1d_pct": 0.67,
        "open_price": 2730.00,
        "high_price": 2760.00,
        "low_price": 2722.50,
        "previous_close": 2727.60,
        "volume": 2150000,
        "week_52_high": 3035.00,
        "week_52_low": 2170.25,
        "description": "Hindustan Unilever Limited (HUL) is India's largest FMCG company with a heritage of over 90 years. HUL touches 9 out of 10 Indian households across personal wash, fabric cleaning, skin care, oral care, tea, coffee, and packaged foods.",
        "fundamentals": {
            "market_cap": 645200.0,
            "pe_ratio": 59.2,
            "pb_ratio": 12.4,
            "ev_to_ebitda": 41.8,
            "roe": 20.4,
            "roce": 27.5,
            "debt_to_equity": 0.02,
            "dividend_yield": 1.52,
            "revenue_growth_yoy": 4.8,
            "profit_growth_yoy": 6.2,
            "eps": 44.50,
            "operating_margin": 23.8,
            "net_margin": 16.9,
            "total_debt": 1100.0,
            "free_cash_flow": 10500.0,
            "promoter_holding": 61.9,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 12.8,
            "dii_holding": 14.1,
            "rsi_14": 52.4,
            "source": "Audited FY25 Annual Report & BSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "RELIANCE": {
        "symbol": "RELIANCE",
        "company_name": "Reliance Industries Limited",
        "sector": "Energy & Petrochemicals",
        "industry": "Oil & Gas Refining / Telecom / Retail",
        "current_price": 2985.40,
        "change_1d": 42.10,
        "change_1d_pct": 1.43,
        "open_price": 2950.00,
        "high_price": 2998.00,
        "low_price": 2945.10,
        "previous_close": 2943.30,
        "volume": 8420150,
        "week_52_high": 3217.90,
        "week_52_low": 2220.30,
        "description": "Reliance Industries Limited is India's largest private sector corporation with businesses spanning energy, petrochemicals, telecommunications (Jio), retail, and new green energy materials.",
        "fundamentals": {
            "market_cap": 2020450.0,
            "pe_ratio": 28.4,
            "pb_ratio": 2.55,
            "ev_to_ebitda": 13.8,
            "roe": 9.4,
            "roce": 10.2,
            "debt_to_equity": 0.42,
            "dividend_yield": 0.34,
            "revenue_growth_yoy": 11.2,
            "profit_growth_yoy": 8.7,
            "eps": 105.12,
            "operating_margin": 17.8,
            "net_margin": 8.4,
            "total_debt": 312000.0,
            "free_cash_flow": 48200.0,
            "promoter_holding": 50.3,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 22.1,
            "dii_holding": 16.4,
            "rsi_14": 58.4,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "TCS": {
        "symbol": "TCS",
        "company_name": "Tata Consultancy Services Ltd",
        "sector": "Information Technology",
        "industry": "IT Services & Consulting",
        "current_price": 4280.75,
        "change_1d": -35.20,
        "change_1d_pct": -0.82,
        "open_price": 4310.00,
        "high_price": 4330.00,
        "low_price": 4260.00,
        "previous_close": 4315.95,
        "volume": 2814000,
        "week_52_high": 4585.90,
        "week_52_low": 3313.00,
        "description": "Tata Consultancy Services is a world-leading IT services, consulting, and business solutions enterprise that partners with global giants in their digital transformation journeys.",
        "fundamentals": {
            "market_cap": 1548200.0,
            "pe_ratio": 32.8,
            "pb_ratio": 15.2,
            "ev_to_ebitda": 23.4,
            "roe": 48.2,
            "roce": 61.5,
            "debt_to_equity": 0.0,
            "dividend_yield": 1.75,
            "revenue_growth_yoy": 7.4,
            "profit_growth_yoy": 9.1,
            "eps": 130.50,
            "operating_margin": 26.2,
            "net_margin": 19.3,
            "total_debt": 0.0,
            "free_cash_flow": 44100.0,
            "promoter_holding": 71.8,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 12.5,
            "dii_holding": 10.3,
            "rsi_14": 44.8,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "HDFCBANK": {
        "symbol": "HDFCBANK",
        "company_name": "HDFC Bank Limited",
        "sector": "Financial Services",
        "industry": "Private Sector Bank",
        "current_price": 1645.20,
        "change_1d": 12.80,
        "change_1d_pct": 0.78,
        "open_price": 1630.00,
        "high_price": 1654.00,
        "low_price": 1628.00,
        "previous_close": 1632.40,
        "volume": 14200000,
        "week_52_high": 1794.00,
        "week_52_low": 1363.55,
        "description": "HDFC Bank is India's largest private bank by assets, providing retail banking, wholesale lending, treasury operations, and digital credit solutions.",
        "fundamentals": {
            "market_cap": 1251000.0,
            "pe_ratio": 18.6,
            "pb_ratio": 2.72,
            "ev_to_ebitda": 11.2,
            "roe": 16.8,
            "roce": 15.9,
            "debt_to_equity": 1.15,
            "dividend_yield": 1.18,
            "revenue_growth_yoy": 24.1,
            "profit_growth_yoy": 33.5,
            "eps": 88.45,
            "operating_margin": 32.5,
            "net_margin": 21.0,
            "total_debt": 210000.0,
            "free_cash_flow": 32000.0,
            "promoter_holding": 0.0,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 47.2,
            "dii_holding": 34.1,
            "rsi_14": 54.2,
            "source": "RBI / Exchange Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "INFY": {
        "symbol": "INFY",
        "company_name": "Infosys Limited",
        "sector": "Information Technology",
        "industry": "IT Consulting & Services",
        "current_price": 1892.30,
        "change_1d": 38.60,
        "change_1d_pct": 2.08,
        "open_price": 1860.00,
        "high_price": 1905.00,
        "low_price": 1855.00,
        "previous_close": 1853.70,
        "volume": 6910000,
        "week_52_high": 1990.00,
        "week_52_low": 1358.35,
        "description": "Infosys is a global technology consulting and enterprise software powerhouse specializing in cloud modernization, AI automation, and cybersecurity solutions.",
        "fundamentals": {
            "market_cap": 785600.0,
            "pe_ratio": 29.5,
            "pb_ratio": 9.1,
            "ev_to_ebitda": 20.8,
            "roe": 31.8,
            "roce": 40.5,
            "debt_to_equity": 0.05,
            "dividend_yield": 2.30,
            "revenue_growth_yoy": 6.8,
            "profit_growth_yoy": 8.9,
            "eps": 64.15,
            "operating_margin": 21.5,
            "net_margin": 16.8,
            "total_debt": 4100.0,
            "free_cash_flow": 23500.0,
            "promoter_holding": 14.7,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 33.8,
            "dii_holding": 36.2,
            "rsi_14": 62.1,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "ICICIBANK": {
        "symbol": "ICICIBANK",
        "company_name": "ICICI Bank Limited",
        "sector": "Financial Services",
        "industry": "Banking & Financial Services",
        "current_price": 1215.80,
        "change_1d": 6.40,
        "change_1d_pct": 0.53,
        "open_price": 1210.00,
        "high_price": 1224.00,
        "low_price": 1206.00,
        "previous_close": 1209.40,
        "volume": 9800000,
        "week_52_high": 1332.00,
        "week_52_low": 918.00,
        "description": "ICICI Bank is a premier Indian multinational financial services bank offering consumer, SME, commercial, and investment banking products.",
        "fundamentals": {
            "market_cap": 855000.0,
            "pe_ratio": 17.8,
            "pb_ratio": 3.1,
            "ev_to_ebitda": 10.8,
            "roe": 18.5,
            "roce": 17.2,
            "debt_to_equity": 0.95,
            "dividend_yield": 0.82,
            "revenue_growth_yoy": 19.4,
            "profit_growth_yoy": 24.8,
            "eps": 68.30,
            "operating_margin": 31.0,
            "net_margin": 22.4,
            "total_debt": 140000.0,
            "free_cash_flow": 26000.0,
            "promoter_holding": 0.0,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 44.5,
            "dii_holding": 45.1,
            "rsi_14": 52.6,
            "source": "RBI / Exchange Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "BHARTIARTL": {
        "symbol": "BHARTIARTL",
        "company_name": "Bharti Airtel Limited",
        "sector": "Telecommunication",
        "industry": "Telecom Services & 5G Infrastructure",
        "current_price": 1582.50,
        "change_1d": 24.10,
        "change_1d_pct": 1.55,
        "open_price": 1560.00,
        "high_price": 1590.00,
        "low_price": 1555.00,
        "previous_close": 1558.40,
        "volume": 5210000,
        "week_52_high": 1690.00,
        "week_52_low": 892.00,
        "description": "Bharti Airtel is a leading global telecommunications provider with operations across 18 countries in South Asia and Africa, delivering 5G, enterprise connectivity, and digital payments.",
        "fundamentals": {
            "market_cap": 945000.0,
            "pe_ratio": 72.0,
            "pb_ratio": 8.4,
            "ev_to_ebitda": 14.5,
            "roe": 15.2,
            "roce": 14.8,
            "debt_to_equity": 1.65,
            "dividend_yield": 0.51,
            "revenue_growth_yoy": 14.5,
            "profit_growth_yoy": 38.2,
            "eps": 22.00,
            "operating_margin": 52.4,
            "net_margin": 8.1,
            "total_debt": 185000.0,
            "free_cash_flow": 28400.0,
            "promoter_holding": 53.1,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 24.9,
            "dii_holding": 18.2,
            "rsi_14": 64.8,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "SBIN": {
        "symbol": "SBIN",
        "company_name": "State Bank of India",
        "sector": "Financial Services",
        "industry": "Public Sector Banking",
        "current_price": 792.40,
        "change_1d": -7.30,
        "change_1d_pct": -0.91,
        "open_price": 801.00,
        "high_price": 805.00,
        "low_price": 788.50,
        "previous_close": 799.70,
        "volume": 12800000,
        "week_52_high": 912.00,
        "week_52_low": 555.30,
        "description": "State Bank of India is a Fortune 500 public sector banking institution and the largest lender in India with over 22,000 branches nationwide.",
        "fundamentals": {
            "market_cap": 707000.0,
            "pe_ratio": 10.4,
            "pb_ratio": 1.7,
            "ev_to_ebitda": 8.1,
            "roe": 17.8,
            "roce": 16.4,
            "debt_to_equity": 1.4,
            "dividend_yield": 1.73,
            "revenue_growth_yoy": 18.2,
            "profit_growth_yoy": 21.0,
            "eps": 76.20,
            "operating_margin": 24.5,
            "net_margin": 14.2,
            "total_debt": 380000.0,
            "free_cash_flow": 41000.0,
            "promoter_holding": 57.5,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 10.9,
            "dii_holding": 24.3,
            "rsi_14": 46.5,
            "source": "RBI / Exchange Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "LT": {
        "symbol": "LT",
        "company_name": "Larsen & Toubro Limited",
        "sector": "Infrastructure & Capital Goods",
        "industry": "Engineering & Construction",
        "current_price": 3610.00,
        "change_1d": 54.00,
        "change_1d_pct": 1.52,
        "open_price": 3570.00,
        "high_price": 3635.00,
        "low_price": 3560.00,
        "previous_close": 3556.00,
        "volume": 2150000,
        "week_52_high": 3948.00,
        "week_52_low": 2860.00,
        "description": "Larsen & Toubro is an Indian multinational conglomerate with operations in EPC projects, hi-tech manufacturing, defense engineering, and digital services.",
        "fundamentals": {
            "market_cap": 496000.0,
            "pe_ratio": 36.5,
            "pb_ratio": 5.4,
            "ev_to_ebitda": 19.8,
            "roe": 15.6,
            "roce": 17.2,
            "debt_to_equity": 0.78,
            "dividend_yield": 0.94,
            "revenue_growth_yoy": 20.6,
            "profit_growth_yoy": 24.5,
            "eps": 98.90,
            "operating_margin": 11.4,
            "net_margin": 6.8,
            "total_debt": 98000.0,
            "free_cash_flow": 12800.0,
            "promoter_holding": 0.0,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 23.4,
            "dii_holding": 38.6,
            "rsi_14": 57.1,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "ITC": {
        "symbol": "ITC",
        "company_name": "ITC Limited",
        "sector": "Fast Moving Consumer Goods",
        "industry": "Cigarettes, FMCG, Hotels, Paperboards & Agri-Business",
        "current_price": 498.80,
        "change_1d": -1.20,
        "change_1d_pct": -0.24,
        "open_price": 502.00,
        "high_price": 505.00,
        "low_price": 496.00,
        "previous_close": 500.00,
        "volume": 8400000,
        "week_52_high": 528.50,
        "week_52_low": 399.30,
        "description": "ITC Limited is one of India's foremost private sector companies with a dominant market presence across FMCG foods, personal care, hospitality, paperboards, and agribusiness.",
        "fundamentals": {
            "market_cap": 622000.0,
            "pe_ratio": 29.8,
            "pb_ratio": 8.9,
            "ev_to_ebitda": 21.0,
            "roe": 28.5,
            "roce": 36.8,
            "debt_to_equity": 0.0,
            "dividend_yield": 2.76,
            "revenue_growth_yoy": 7.8,
            "profit_growth_yoy": 10.4,
            "eps": 16.74,
            "operating_margin": 38.2,
            "net_margin": 27.5,
            "total_debt": 0.0,
            "free_cash_flow": 18400.0,
            "promoter_holding": 0.0,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 41.2,
            "dii_holding": 42.6,
            "rsi_14": 49.3,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "TATAMOTORS": {
        "symbol": "TATAMOTORS",
        "company_name": "Tata Motors Limited",
        "sector": "Automotive",
        "industry": "Passenger, Commercial & Luxury Vehicles (JLR)",
        "current_price": 965.30,
        "change_1d": 21.40,
        "change_1d_pct": 2.27,
        "open_price": 948.00,
        "high_price": 972.00,
        "low_price": 944.00,
        "previous_close": 943.90,
        "volume": 7650000,
        "week_52_high": 1179.00,
        "week_52_low": 606.00,
        "description": "Tata Motors is India's leading automotive manufacturer and EV market pioneer, along with its wholly owned British luxury subsidiary Jaguar Land Rover.",
        "fundamentals": {
            "market_cap": 355000.0,
            "pe_ratio": 11.2,
            "pb_ratio": 3.8,
            "ev_to_ebitda": 5.4,
            "roe": 34.2,
            "roce": 22.8,
            "debt_to_equity": 0.85,
            "dividend_yield": 0.62,
            "revenue_growth_yoy": 26.5,
            "profit_growth_yoy": 74.2,
            "eps": 86.10,
            "operating_margin": 14.8,
            "net_margin": 7.2,
            "total_debt": 54000.0,
            "free_cash_flow": 26900.0,
            "promoter_holding": 46.4,
            "promoter_pledge_pct": 1.8,
            "fii_holding": 18.2,
            "dii_holding": 16.9,
            "rsi_14": 61.3,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "KOTAKBANK": {
        "symbol": "KOTAKBANK",
        "company_name": "Kotak Mahindra Bank Limited",
        "sector": "Financial Services",
        "industry": "Private Banking & Asset Management",
        "current_price": 1820.50,
        "change_1d": -8.40,
        "change_1d_pct": -0.46,
        "open_price": 1832.00,
        "high_price": 1845.00,
        "low_price": 1812.00,
        "previous_close": 1828.90,
        "volume": 3420000,
        "week_52_high": 1940.00,
        "week_52_low": 1544.00,
        "description": "Kotak Mahindra Bank is an Indian financial services company offering commercial banking, investment banking, life insurance, and wealth management.",
        "fundamentals": {
            "market_cap": 362000.0,
            "pe_ratio": 21.4,
            "pb_ratio": 2.8,
            "ev_to_ebitda": 13.5,
            "roe": 14.8,
            "roce": 15.2,
            "debt_to_equity": 0.9,
            "dividend_yield": 0.11,
            "revenue_growth_yoy": 15.2,
            "profit_growth_yoy": 18.4,
            "eps": 85.10,
            "operating_margin": 30.2,
            "net_margin": 23.4,
            "total_debt": 75000.0,
            "free_cash_flow": 14200.0,
            "promoter_holding": 25.9,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 38.4,
            "dii_holding": 22.1,
            "rsi_14": 48.9,
            "source": "RBI / Exchange Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "BAJFINANCE": {
        "symbol": "BAJFINANCE",
        "company_name": "Bajaj Finance Limited",
        "sector": "Financial Services",
        "industry": "Non-Banking Financial Company (NBFC)",
        "current_price": 7240.00,
        "change_1d": 115.00,
        "change_1d_pct": 1.61,
        "open_price": 7160.00,
        "high_price": 7280.00,
        "low_price": 7140.00,
        "previous_close": 7125.00,
        "volume": 1210000,
        "week_52_high": 8190.00,
        "week_52_low": 6375.00,
        "description": "Bajaj Finance is India's leading diversified non-banking financial company with omnipresent digital lending, consumer electronics finance, and SME financing.",
        "fundamentals": {
            "market_cap": 447000.0,
            "pe_ratio": 29.8,
            "pb_ratio": 5.4,
            "ev_to_ebitda": 16.2,
            "roe": 22.1,
            "roce": 21.5,
            "debt_to_equity": 3.4,
            "dividend_yield": 0.50,
            "revenue_growth_yoy": 28.4,
            "profit_growth_yoy": 22.8,
            "eps": 242.80,
            "operating_margin": 34.5,
            "net_margin": 26.2,
            "total_debt": 280000.0,
            "free_cash_flow": 18200.0,
            "promoter_holding": 54.7,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 20.8,
            "dii_holding": 14.6,
            "rsi_14": 56.7,
            "source": "RBI / Exchange Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "MARUTI": {
        "symbol": "MARUTI",
        "company_name": "Maruti Suzuki India Limited",
        "sector": "Automotive",
        "industry": "Passenger Vehicles & Hybrid Powertrains",
        "current_price": 12450.00,
        "change_1d": 180.00,
        "change_1d_pct": 1.47,
        "open_price": 12300.00,
        "high_price": 12520.00,
        "low_price": 12280.00,
        "previous_close": 12270.00,
        "volume": 580000,
        "week_52_high": 13680.00,
        "week_52_low": 9735.00,
        "description": "Maruti Suzuki is the undisputed market leader in the Indian passenger vehicle industry with over 40% market share and extensive export presence in Latin America and Africa.",
        "fundamentals": {
            "market_cap": 391000.0,
            "pe_ratio": 28.5,
            "pb_ratio": 4.6,
            "ev_to_ebitda": 18.2,
            "roe": 17.5,
            "roce": 22.1,
            "debt_to_equity": 0.01,
            "dividend_yield": 1.01,
            "revenue_growth_yoy": 16.4,
            "profit_growth_yoy": 48.2,
            "eps": 436.50,
            "operating_margin": 12.1,
            "net_margin": 9.4,
            "total_debt": 1200.0,
            "free_cash_flow": 14800.0,
            "promoter_holding": 58.2,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 19.5,
            "dii_holding": 16.2,
            "rsi_14": 55.4,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "SUNPHARMA": {
        "symbol": "SUNPHARMA",
        "company_name": "Sun Pharmaceutical Industries Limited",
        "sector": "Healthcare & Pharmaceuticals",
        "industry": "Specialty Pharmaceuticals & Active Ingredients",
        "current_price": 1890.00,
        "change_1d": 25.40,
        "change_1d_pct": 1.36,
        "open_price": 1870.00,
        "high_price": 1905.00,
        "low_price": 1865.00,
        "previous_close": 1864.60,
        "volume": 1840000,
        "week_52_high": 1960.00,
        "week_52_low": 1110.00,
        "description": "Sun Pharma is India's largest pharmaceutical company and the 4th largest global specialty generic enterprise, operating across 100+ markets worldwide.",
        "fundamentals": {
            "market_cap": 453000.0,
            "pe_ratio": 42.1,
            "pb_ratio": 6.8,
            "ev_to_ebitda": 26.5,
            "roe": 16.8,
            "roce": 19.2,
            "debt_to_equity": 0.08,
            "dividend_yield": 0.72,
            "revenue_growth_yoy": 10.5,
            "profit_growth_yoy": 15.8,
            "eps": 44.80,
            "operating_margin": 27.5,
            "net_margin": 20.1,
            "total_debt": 5200.0,
            "free_cash_flow": 11400.0,
            "promoter_holding": 54.5,
            "promoter_pledge_pct": 1.2,
            "fii_holding": 17.8,
            "dii_holding": 20.1,
            "rsi_14": 63.8,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "TITAN": {
        "symbol": "TITAN",
        "company_name": "Titan Company Limited",
        "sector": "Consumer Discretionary",
        "industry": "Jewellery (Tanishq), Watches & Eyewear",
        "current_price": 3710.00,
        "change_1d": -15.00,
        "change_1d_pct": -0.40,
        "open_price": 3730.00,
        "high_price": 3755.00,
        "low_price": 3690.00,
        "previous_close": 3725.00,
        "volume": 1150000,
        "week_52_high": 3886.95,
        "week_52_low": 2980.00,
        "description": "Titan Company is an Indian luxury consumer goods enterprise that transformed India's watch and jewellery industry under the Tata banner.",
        "fundamentals": {
            "market_cap": 329000.0,
            "pe_ratio": 89.4,
            "pb_ratio": 24.2,
            "ev_to_ebitda": 52.0,
            "roe": 31.4,
            "roce": 35.8,
            "debt_to_equity": 0.65,
            "dividend_yield": 0.30,
            "revenue_growth_yoy": 22.8,
            "profit_growth_yoy": 12.5,
            "eps": 41.50,
            "operating_margin": 10.4,
            "net_margin": 7.1,
            "total_debt": 8900.0,
            "free_cash_flow": 3800.0,
            "promoter_holding": 52.9,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 18.2,
            "dii_holding": 11.4,
            "rsi_14": 51.2,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "ASIANPAINT": {
        "symbol": "ASIANPAINT",
        "company_name": "Asian Paints Limited",
        "sector": "Consumer Discretionary",
        "industry": "Paints, Coatings & Home Décor",
        "current_price": 3215.00,
        "change_1d": 32.00,
        "change_1d_pct": 1.01,
        "open_price": 3190.00,
        "high_price": 3230.00,
        "low_price": 3180.00,
        "previous_close": 3183.00,
        "volume": 1250000,
        "week_52_high": 3568.00,
        "week_52_low": 2685.85,
        "description": "Asian Paints is India's largest and Asia's third largest paint company, manufacturing decorative and industrial coatings with unmatched supply chain depth.",
        "fundamentals": {
            "market_cap": 308000.0,
            "pe_ratio": 55.4,
            "pb_ratio": 17.8,
            "ev_to_ebitda": 36.2,
            "roe": 33.5,
            "roce": 42.1,
            "debt_to_equity": 0.08,
            "dividend_yield": 1.05,
            "revenue_growth_yoy": 5.2,
            "profit_growth_yoy": 7.4,
            "eps": 58.00,
            "operating_margin": 21.2,
            "net_margin": 15.1,
            "total_debt": 1500.0,
            "free_cash_flow": 4600.0,
            "promoter_holding": 52.6,
            "promoter_pledge_pct": 5.4,
            "fii_holding": 15.8,
            "dii_holding": 12.9,
            "rsi_14": 49.8,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "TATASTEEL": {
        "symbol": "TATASTEEL",
        "company_name": "Tata Steel Limited",
        "sector": "Metals & Mining",
        "industry": "Iron & Steel Production",
        "current_price": 158.40,
        "change_1d": 2.80,
        "change_1d_pct": 1.80,
        "open_price": 156.00,
        "high_price": 159.50,
        "low_price": 155.20,
        "previous_close": 155.60,
        "volume": 28400000,
        "week_52_high": 184.60,
        "week_52_low": 118.40,
        "description": "Tata Steel is one of the world's most geographically diversified steel producers with operations in India, UK, and the Netherlands.",
        "fundamentals": {
            "market_cap": 197000.0,
            "pe_ratio": 48.0,
            "pb_ratio": 2.1,
            "ev_to_ebitda": 9.4,
            "roe": 4.5,
            "roce": 8.2,
            "debt_to_equity": 0.95,
            "dividend_yield": 2.27,
            "revenue_growth_yoy": -3.8,
            "profit_growth_yoy": 12.0,
            "eps": 3.30,
            "operating_margin": 10.8,
            "net_margin": 2.1,
            "total_debt": 87000.0,
            "free_cash_flow": 8200.0,
            "promoter_holding": 33.2,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 19.8,
            "dii_holding": 23.5,
            "rsi_14": 53.8,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "NTPC": {
        "symbol": "NTPC",
        "company_name": "NTPC Limited",
        "sector": "Utilities & Power",
        "industry": "Power Generation & Renewable Transition",
        "current_price": 412.50,
        "change_1d": 6.80,
        "change_1d_pct": 1.68,
        "open_price": 407.00,
        "high_price": 415.00,
        "low_price": 405.00,
        "previous_close": 405.70,
        "volume": 14200000,
        "week_52_high": 448.45,
        "week_52_low": 232.00,
        "description": "NTPC is India's largest energy conglomerate with 76+ GW installed capacity, rapidly expanding into solar, wind, and green hydrogen power.",
        "fundamentals": {
            "market_cap": 400000.0,
            "pe_ratio": 18.2,
            "pb_ratio": 2.4,
            "ev_to_ebitda": 11.0,
            "roe": 13.8,
            "roce": 12.4,
            "debt_to_equity": 1.35,
            "dividend_yield": 2.10,
            "revenue_growth_yoy": 8.4,
            "profit_growth_yoy": 18.5,
            "eps": 22.65,
            "operating_margin": 25.4,
            "net_margin": 12.8,
            "total_debt": 210000.0,
            "free_cash_flow": 16400.0,
            "promoter_holding": 51.1,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 17.5,
            "dii_holding": 27.2,
            "rsi_14": 62.4,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "POWERGRID": {
        "symbol": "POWERGRID",
        "company_name": "Power Grid Corporation of India",
        "sector": "Utilities & Power",
        "industry": "Electric Power Transmission",
        "current_price": 338.20,
        "change_1d": 3.40,
        "change_1d_pct": 1.02,
        "open_price": 336.00,
        "high_price": 341.00,
        "low_price": 334.50,
        "previous_close": 334.80,
        "volume": 11200000,
        "week_52_high": 366.00,
        "week_52_low": 196.00,
        "description": "Power Grid is India's central transmission utility, transmitting approximately 85% of India's total power generated across an interstate network.",
        "fundamentals": {
            "market_cap": 314000.0,
            "pe_ratio": 19.5,
            "pb_ratio": 3.6,
            "ev_to_ebitda": 10.4,
            "roe": 18.9,
            "roce": 15.2,
            "debt_to_equity": 1.45,
            "dividend_yield": 3.32,
            "revenue_growth_yoy": 6.8,
            "profit_growth_yoy": 11.2,
            "eps": 17.35,
            "operating_margin": 87.5,
            "net_margin": 33.2,
            "total_debt": 124000.0,
            "free_cash_flow": 19500.0,
            "promoter_holding": 51.3,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 22.8,
            "dii_holding": 19.4,
            "rsi_14": 57.8,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "ADANIENT": {
        "symbol": "ADANIENT",
        "company_name": "Adani Enterprises Limited",
        "sector": "Conglomerates",
        "industry": "Mining, Airports, Roads & Data Centers",
        "current_price": 3120.00,
        "change_1d": 45.00,
        "change_1d_pct": 1.46,
        "open_price": 3085.00,
        "high_price": 3145.00,
        "low_price": 3070.00,
        "previous_close": 3075.00,
        "volume": 1950000,
        "week_52_high": 3743.00,
        "week_52_low": 2142.00,
        "description": "Adani Enterprises is the flagship business incubator of the Adani Group, with businesses across green hydrogen, airports, data centers, roads, and primary resources.",
        "fundamentals": {
            "market_cap": 355000.0,
            "pe_ratio": 98.4,
            "pb_ratio": 8.5,
            "ev_to_ebitda": 28.4,
            "roe": 9.2,
            "roce": 11.4,
            "debt_to_equity": 1.25,
            "dividend_yield": 0.04,
            "revenue_growth_yoy": 12.8,
            "profit_growth_yoy": 42.1,
            "eps": 31.70,
            "operating_margin": 11.5,
            "net_margin": 3.2,
            "total_debt": 58000.0,
            "free_cash_flow": 4200.0,
            "promoter_holding": 72.6,
            "promoter_pledge_pct": 2.1,
            "fii_holding": 14.5,
            "dii_holding": 6.8,
            "rsi_14": 54.6,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "ZOMATO": {
        "symbol": "ZOMATO",
        "company_name": "Zomato Limited",
        "sector": "Consumer Tech",
        "industry": "Online Food Delivery & Quick Commerce (Blinkit)",
        "current_price": 272.40,
        "change_1d": 6.80,
        "change_1d_pct": 2.56,
        "open_price": 266.00,
        "high_price": 275.00,
        "low_price": 264.50,
        "previous_close": 265.60,
        "volume": 32400000,
        "week_52_high": 298.00,
        "week_52_low": 98.20,
        "description": "Zomato is an Indian multinational restaurant aggregator and quick-commerce company operating food ordering, Blinkit grocery logistics, and Hyperpure B2B supplies.",
        "fundamentals": {
            "market_cap": 241000.0,
            "pe_ratio": 142.0,
            "pb_ratio": 11.8,
            "ev_to_ebitda": 68.5,
            "roe": 6.5,
            "roce": 8.4,
            "debt_to_equity": 0.01,
            "dividend_yield": 0.0,
            "revenue_growth_yoy": 68.4,
            "profit_growth_yoy": 240.0,
            "eps": 1.92,
            "operating_margin": 8.5,
            "net_margin": 5.2,
            "total_debt": 450.0,
            "free_cash_flow": 3100.0,
            "promoter_holding": 0.0,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 54.2,
            "dii_holding": 18.5,
            "rsi_14": 68.2,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "BEL": {
        "symbol": "BEL",
        "company_name": "Bharat Electronics Limited",
        "sector": "Defense & Aerospace",
        "industry": "Defense Radar, Avionics & Electronic Warfare",
        "current_price": 305.50,
        "change_1d": 5.20,
        "change_1d_pct": 1.73,
        "open_price": 301.00,
        "high_price": 308.00,
        "low_price": 299.50,
        "previous_close": 300.30,
        "volume": 9400000,
        "week_52_high": 340.50,
        "week_52_low": 132.50,
        "description": "Bharat Electronics Limited (BEL) is a Navratna PSU under the Ministry of Defence, manufacturing state-of-the-art radar systems, sonar, electronic warfare, and missile guidance electronics.",
        "fundamentals": {
            "market_cap": 223000.0,
            "pe_ratio": 48.2,
            "pb_ratio": 12.5,
            "ev_to_ebitda": 34.1,
            "roe": 26.5,
            "roce": 35.8,
            "debt_to_equity": 0.0,
            "dividend_yield": 0.72,
            "revenue_growth_yoy": 15.4,
            "profit_growth_yoy": 33.2,
            "eps": 6.34,
            "operating_margin": 24.8,
            "net_margin": 19.5,
            "total_debt": 0.0,
            "free_cash_flow": 4900.0,
            "promoter_holding": 51.1,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 17.4,
            "dii_holding": 23.8,
            "rsi_14": 61.2,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    },
    "TRENT": {
        "symbol": "TRENT",
        "company_name": "Trent Limited",
        "sector": "Consumer Discretionary",
        "industry": "Apparel & Retail (Westside, Zudio, Star)",
        "current_price": 7120.00,
        "change_1d": 140.00,
        "change_1d_pct": 2.01,
        "open_price": 7000.00,
        "high_price": 7180.00,
        "low_price": 6970.00,
        "previous_close": 6980.00,
        "volume": 1250000,
        "week_52_high": 7940.00,
        "week_52_low": 2040.00,
        "description": "Trent is Tata Group's retail enterprise running Westside, Zudio value fashion, and Star hypermarkets, known for high capital efficiency and rapid private-label store expansion.",
        "fundamentals": {
            "market_cap": 253000.0,
            "pe_ratio": 165.0,
            "pb_ratio": 44.2,
            "ev_to_ebitda": 82.0,
            "roe": 32.5,
            "roce": 31.2,
            "debt_to_equity": 0.12,
            "dividend_yield": 0.05,
            "revenue_growth_yoy": 52.4,
            "profit_growth_yoy": 120.5,
            "eps": 43.15,
            "operating_margin": 16.2,
            "net_margin": 9.8,
            "total_debt": 800.0,
            "free_cash_flow": 3200.0,
            "promoter_holding": 37.0,
            "promoter_pledge_pct": 0.0,
            "fii_holding": 27.8,
            "dii_holding": 15.2,
            "rsi_14": 66.4,
            "source": "Audited Annual Report & NSE Filings",
            "as_of_date": "Q1 FY26"
        }
    }
}

CORPORATE_ACTIONS_DATA: List[Dict[str, Any]] = [
    {
        "symbol": "HINDUNILVR",
        "company_name": "Hindustan Unilever Limited",
        "action_type": "DIVIDEND",
        "ex_date": "2026-06-18",
        "record_date": "2026-06-19",
        "details": "Final Dividend of ₹24.00 per equity share",
        "impact_summary": "Cash payout of ₹24/share credited directly to bank account."
    },
    {
        "symbol": "RELIANCE",
        "company_name": "Reliance Industries Limited",
        "action_type": "BONUS",
        "ex_date": "2026-08-14",
        "record_date": "2026-08-15",
        "details": "Bonus Issue 1:1 (1 bonus share for every 1 share held)",
        "impact_summary": "Doubles share quantity; share price halved on ex-date."
    },
    {
        "symbol": "TCS",
        "company_name": "Tata Consultancy Services Ltd",
        "action_type": "DIVIDEND",
        "ex_date": "2026-07-16",
        "record_date": "2026-07-17",
        "details": "Interim Dividend of ₹10.00 + Special Dividend of ₹18.00 per share",
        "impact_summary": "Total cash dividend ₹28.00/share."
    },
    {
        "symbol": "INFY",
        "company_name": "Infosys Limited",
        "action_type": "DIVIDEND",
        "ex_date": "2026-05-31",
        "record_date": "2026-06-01",
        "details": "Final Dividend of ₹20.00 and Special Dividend of ₹8.00",
        "impact_summary": "₹28/share annual payout."
    },
    {
        "symbol": "ITC",
        "company_name": "ITC Limited",
        "action_type": "DEMERGER",
        "ex_date": "2026-04-10",
        "record_date": "2026-04-11",
        "details": "Demerger of ITC Hotels Limited (1 hotel share for every 10 ITC shares)",
        "impact_summary": "Entitled shareholders receive ITC Hotels shares credited to demat."
    },
    {
        "symbol": "TRENT",
        "company_name": "Trent Limited",
        "action_type": "DIVIDEND",
        "ex_date": "2026-05-22",
        "record_date": "2026-05-23",
        "details": "Dividend of ₹3.20 per share",
        "impact_summary": "Cash distribution to eligible holders."
    }
]

BULK_BLOCK_DEALS_DATA: List[Dict[str, Any]] = [
    {
        "symbol": "HINDUNILVR",
        "company_name": "Hindustan Unilever Limited",
        "deal_type": "BLOCK",
        "trade_date": "2026-08-20",
        "client_name": "Societe Generale Asia Fund",
        "deal_side": "BUY",
        "quantity": 1450000,
        "trade_price": 2715.50,
        "value_in_cr": 393.75
    },
    {
        "symbol": "ZOMATO",
        "company_name": "Zomato Limited",
        "deal_type": "BULK",
        "trade_date": "2026-08-12",
        "client_name": "Morgan Stanley Asia Singapore Pte",
        "deal_side": "BUY",
        "quantity": 12500000,
        "trade_price": 262.30,
        "value_in_cr": 327.87
    },
    {
        "symbol": "RELIANCE",
        "company_name": "Reliance Industries Limited",
        "deal_type": "BLOCK",
        "trade_date": "2026-07-28",
        "client_name": "Government of Singapore Investment Corp (GIC)",
        "deal_side": "BUY",
        "quantity": 2800000,
        "trade_price": 2960.00,
        "value_in_cr": 828.80
    },
    {
        "symbol": "TRENT",
        "company_name": "Trent Limited",
        "deal_type": "BULK",
        "trade_date": "2026-09-02",
        "client_name": "Vanguard Emerging Markets Stock Index Fund",
        "deal_side": "BUY",
        "quantity": 850000,
        "trade_price": 7050.00,
        "value_in_cr": 599.25
    }
]

INSIDER_TRADES_DATA: List[Dict[str, Any]] = [
    {
        "symbol": "HINDUNILVR",
        "insider_name": "Priya Nair",
        "designation": "Executive Director",
        "regulation": "SEBI PIT Reg 7(2)",
        "transaction_type": "ESOP_ALLOTMENT",
        "quantity": 8500,
        "value_in_lakhs": 233.4,
        "filing_date": "2026-08-25"
    },
    {
        "symbol": "INFY",
        "insider_name": "Salil Parekh",
        "designation": "Chief Executive Officer & MD",
        "regulation": "SEBI PIT Reg 7(2)",
        "transaction_type": "ESOP_ALLOTMENT",
        "quantity": 15000,
        "value_in_lakhs": 283.8,
        "filing_date": "2026-07-14"
    },
    {
        "symbol": "BHARTIARTL",
        "insider_name": "Gopal Vittal",
        "designation": "Managing Director & CEO",
        "regulation": "SEBI PIT Reg 7(2)",
        "transaction_type": "MARKET_PURCHASE",
        "quantity": 12000,
        "value_in_lakhs": 189.9,
        "filing_date": "2026-06-18"
    }
]

INDEX_CONSTITUENT_CHANGES: List[Dict[str, Any]] = [
    {
        "index_name": "NIFTY 50",
        "effective_date": "2024-09-30",
        "added_symbol": "TRENT",
        "removed_symbol": "DIVISLAB",
        "reason": "Semi-annual index rebalancing based on 6-month average free-float market cap."
    },
    {
        "index_name": "NIFTY 50",
        "effective_date": "2024-09-30",
        "added_symbol": "BEL",
        "removed_symbol": "LTIM",
        "reason": "Defense PSU met market capitalization eligibility criteria."
    },
    {
        "index_name": "NIFTY 50",
        "effective_date": "2024-03-28",
        "added_symbol": "SHRIRAMFIN",
        "removed_symbol": "UPL",
        "reason": "Free-float capitalization and liquidity ranking reclassification."
    }
]

NEWS_FEED_DATA = [
    {
        "symbol": "HINDUNILVR",
        "headline": "Hindustan Unilever Strengthens Premium Beauty & Well-being Portfolio; Volume Growth Recovers",
        "summary": "HUL announced strong traction across modern trade and digital quick commerce channels, with green shoots in rural demand across Central and Northern India.",
        "source": "The Economic Times",
        "url": "https://economictimes.indiatimes.com",
        "sentiment": "POSITIVE",
        "sentiment_score": 0.74,
        "published_at": "2026-09-08T11:20:00Z"
    },
    {
        "symbol": "RELIANCE",
        "headline": "Reliance Jio and NVIDIA Partner to Build Sovereign AI Cloud Infrastructure in India",
        "summary": "Reliance Industries expands its digital super-ecosystem with high-capacity accelerated computing clusters aimed at Indian enterprises, sovereign AI models, and 5G network intelligence.",
        "source": "Financial Express",
        "url": "https://www.financialexpress.com",
        "sentiment": "POSITIVE",
        "sentiment_score": 0.82,
        "published_at": "2026-09-09T14:30:00Z"
    },
    {
        "symbol": "TCS",
        "headline": "TCS Reports Resilient Deal Pipeline; Margins Moderate on Talent Investments",
        "summary": "Tata Consultancy Services maintains strong BFSI deal pipeline in North America and Europe while noting mild client caution around discretionary spending cycles.",
        "source": "Mint",
        "url": "https://www.livemint.com",
        "sentiment": "NEUTRAL",
        "sentiment_score": 0.12,
        "published_at": "2026-09-08T09:15:00Z"
    },
    {
        "symbol": "HDFCBANK",
        "headline": "HDFC Bank Loan-to-Deposit Ratio Normalizes Toward Historical Trend",
        "summary": "Management commentary highlights disciplined credit expansion and aggressive deposit accretion across semi-urban branches post-merger integration.",
        "source": "Business Standard",
        "url": "https://www.business-standard.com",
        "sentiment": "POSITIVE",
        "sentiment_score": 0.65,
        "published_at": "2026-09-07T16:45:00Z"
    },
    {
        "symbol": "TATAMOTORS",
        "headline": "Tata Motors Demerger on Schedule; EV Volume Surges 34% YoY",
        "summary": "Separation of commercial and passenger vehicle segments gains regulatory clearance; JLR order bank remains resilient with order books exceeding 130,000 units.",
        "source": "CNBC-TV18",
        "url": "https://www.cnbctv18.com",
        "sentiment": "POSITIVE",
        "sentiment_score": 0.88,
        "published_at": "2026-09-09T08:00:00Z"
    },
    {
        "symbol": "TRENT",
        "headline": "Trent Expands Zudio Store Network to 600+ Outlets Across Tier 2 and Tier 3 Cities",
        "summary": "Fast-fashion powerhouse maintains double-digit same-store sales growth powered by high inventory turns and responsive supply chain.",
        "source": "Mint",
        "url": "https://www.livemint.com",
        "sentiment": "POSITIVE",
        "sentiment_score": 0.85,
        "published_at": "2026-09-05T12:00:00Z"
    }
]

FINANCIAL_DOCUMENTS_DATA = [
    {
        "symbol": "HINDUNILVR",
        "title": "Hindustan Unilever Limited - Integrated Annual Report FY2025",
        "doc_type": "ANNUAL_REPORT",
        "fiscal_year": "FY2024-25",
        "content": (
            "Hindustan Unilever Limited Chairman's Statement: In FY25, turnover crossed ₹60,500 Crores with underlying volume growth "
            "of 4%. Operating margin was sustained at 23.8% through disciplined cost management and supply chain digitization. "
            "Our Beauty & Personal Care division launched 45 new SKUs, while Home Care expanded liquid detergents across Tier 2 towns. "
            "Zero promoter pledge was maintained. Total dividend paid for the year was ₹42 per share."
        )
    },
    {
        "symbol": "RELIANCE",
        "title": "Reliance Industries Limited - Annual Report FY2025",
        "doc_type": "ANNUAL_REPORT",
        "fiscal_year": "FY2024-25",
        "content": (
            "Consolidated EBITDA crossed ₹1,78,000 Crores. Digital services arm Jio recorded 490 million subscribers with 5G rollout "
            "completed across all 22 telecom circles. Retail physical footprint expanded to 18,800 stores. Oil to Chemicals segment "
            "navigated global refining margin volatility with high feedstock flexibility. Green Energy Gigafactory in Jamnagar initiated "
            "phase 1 solar cell and module production. Net debt to EBITDA remains within target ratio of 0.7x."
        )
    },
    {
        "symbol": "TCS",
        "title": "Tata Consultancy Services - Audited Financial Results FY2025",
        "doc_type": "ANNUAL_REPORT",
        "fiscal_year": "FY2024-25",
        "content": (
            "Total revenue reached ₹2,40,893 Crores, representing 6.8% YoY constant currency growth. Operating margin stood at 26.0%. "
            "Net income grew to ₹46,099 Crores. The company deployed over 350,000 associates trained on foundational GenAI technologies. "
            "Total Contract Value (TCV) stood at $42.7 billion with significant renewals in banking and healthcare. Dividend per share "
            "totaled ₹73 for the fiscal year."
        )
    }
]
